### PR TITLE
Removing arbitrary width of dropdown menu name

### PR DESCRIPTION
**Pull request by DavidHollins6**
### 💬 Description
This fix is best explained in picture form.

BEFORE:
before

AFTER:
Screenshot 2020-11-18 at 14 27 53

### 🚪 Start Points
_Where is a good place to start the review? If there are multiple changes it may be worth listing multiple files._
### 👫 Related PRs (optional)
_Any PRs that relate to the changes._

### ✅ Checklist
- [ ] Tests written
- [ ] Browser tested
- [ ] Added to documentation
- [ ] Added to storybook

### CODE REVIEW

**Comment by DavidHollins6** [comment]
[Selected template in the template dropdown breaks layout](https://trello.com/c/cCNGUKHw/124-selected-template-in-the-template-dropdown-breaks-layout)

**Comment by DavidHollins6** [comment]
[Selected template in the template dropdown breaks layout](https://trello.com/c/cCNGUKHw/124-selected-template-in-the-template-dropdown-breaks-layout)

**Comment by DavidHollins6** [comment]
[Position of template dropdown is borked](https://trello.com/c/DTGboKKo/123-position-of-template-dropdown-is-borked)

**Comment by DavidHollins6** [comment]
[Selected template in the template dropdown breaks layout](https://trello.com/c/cCNGUKHw/124-selected-template-in-the-template-dropdown-breaks-layout)

**Review by kyleharper — APPROVED** [review]

**Review by altaudio — APPROVED** [review]

**Pull request merged**
