### PR TITLE
Refactor SearchInput to no longer be controlled

### PR DESCRIPTION
**Pull request by DavidHollins6**
### 👀 Overview
A lot of work has been done around filtering in the app, as a result there has been a need to control the Search Input, either to clear it or update it from the app.
### 💬 Description
I have removed the local state and exposed it's API. It is now going to be controlled through the props instead.

**This will be a minor version update.**

### ✅ Checklist
- [x] Tests written
- [x] Browser tested
- [ ] Added to documentation
- [x] Added to storybook

### CODE REVIEW

**Comment by DavidHollins6** [comment]
> Nice, but do we not need to update the test / storybook also?

So all the tests passed when I ran `yarn test`, and they pass in the CI. But when I run them through the webstorm test runner the `SearchInput` ones run and fail...

This is similar to the issue we were having last week, I'm close to renaming this whole component & tests

**Comment by petemcfarlane** [comment]
@DavidHollins6 that's disturbing, I wonder how long that's been happening. Do the others know about that also? CC @altaudio @kyleharper @AmeeMorris 

@amee It does introduce breaking changes, hence the minor version, but I think @DavidHollins6 will fix those in the app with the release 👍

**Comment by kyleharper** [comment]
@DavidHollins6 the UI is used;

- account dashboard
- old content hub release archive items (turn your flag off to see)
- new content hub

The new content hub you have sorted (with the work you mentioned) but what about the others? 🤔

**Comment by DavidHollins6** [comment]
> @DavidHollins6 the UI is used;
> 
> * account dashboard
> * old content hub release archive items (turn your flag off to see)
> * new content hub
> 
> The new content hub you have sorted (with the work you mentioned) but what about the others? 🤔

This PR should have all of that in: https://github.com/gathercontent/app/pull/1925

**Pull request merged**
